from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from datetime import datetime
import os

PRIMARY = RGBColor(31, 78, 121)
ACCENT = RGBColor(68, 114, 196)
WHITE = RGBColor(255, 255, 255)


class PPTAgent:

    def add_header(self, slide, prs):

        header = slide.shapes.add_shape(
            1,
            0,
            0,
            prs.slide_width,
            Inches(0.35)
        )

        header.fill.solid()
        header.fill.fore_color.rgb = PRIMARY
        header.line.color.rgb = PRIMARY

    def add_card(
        self,
        slide,
        left,
        top,
        width,
        height,
        title,
        value
    ):

        card = slide.shapes.add_shape(
            1,
            left,
            top,
            width,
            height
        )

        card.fill.solid()
        card.fill.fore_color.rgb = ACCENT
        card.line.color.rgb = ACCENT

        tf = card.text_frame
        tf.clear()

        p1 = tf.paragraphs[0]
        p1.text = title
        p1.font.size = Pt(14)
        p1.font.bold = True
        p1.font.color.rgb = WHITE

        p2 = tf.add_paragraph()
        p2.text = str(value)
        p2.font.size = Pt(24)
        p2.font.bold = True
        p2.font.color.rgb = WHITE

    def clean_insights(self, insights):

        lines = []

        for line in insights.split("\n"):

            line = line.strip()

            if (
                len(line) > 20
                and not line.startswith("#")
                and "---" not in line
            ):
                lines.append(line)

        return lines[:5]

    def generate_ppt(
        self,
        analysis_result,
        insights,
        chart_paths
    ):

        prs = Presentation()

        # =========================
        # COVER PAGE
        # =========================

        slide = prs.slides.add_slide(
            prs.slide_layouts[0]
        )

        slide.shapes.title.text = (
            "Analytics Report"
        )

        slide.placeholders[1].text = (
            f"Generated by Analytics AI\n"
            f"{datetime.now().strftime('%d %B %Y')}"
        )

        # =========================
        # BUSINESS OVERVIEW
        # =========================

        slide = prs.slides.add_slide(
            prs.slide_layouts[5]
        )

        self.add_header(slide, prs)

        title = slide.shapes.title

        if title:
            title.text = "Business Overview"
        else:
            slide.shapes.add_textbox(
                Inches(0.3),
                Inches(0.5),
                Inches(4),
                Inches(0.5)
            ).text = "Business Overview"

        self.add_card(
            slide,
            Inches(0.5),
            Inches(1.5),
            Inches(2),
            Inches(1.2),
            "Records",
            analysis_result["rows"]
        )

        self.add_card(
            slide,
            Inches(3),
            Inches(1.5),
            Inches(2),
            Inches(1.2),
            "Columns",
            analysis_result["columns"]
        )

        self.add_card(
            slide,
            Inches(5.5),
            Inches(1.5),
            Inches(2),
            Inches(1.2),
            "Numeric",
            len(
                analysis_result[
                    "numeric_columns"
                ]
            )
        )

        self.add_card(
            slide,
            Inches(0.5),
            Inches(3),
            Inches(2),
            Inches(1.2),
            "Categories",
            len(
                analysis_result[
                    "categorical_columns"
                ]
            )
        )

        # =========================
        # EXECUTIVE SUMMARY
        # =========================

        slide = prs.slides.add_slide(
            prs.slide_layouts[1]
        )

        self.add_header(slide, prs)

        slide.shapes.title.text = (
            "Executive Summary"
        )

        summary = f"""
• Dataset contains {analysis_result['rows']} records.

• Analysis completed successfully.

• {len(analysis_result['numeric_columns'])} key numerical metrics identified.

• {len(analysis_result['categorical_columns'])} business categories detected.

• Visual trends and KPI insights generated.
"""

        slide.placeholders[1].text = summary

        # =========================
        # KPI DETAILS
        # =========================

        slide = prs.slides.add_slide(
            prs.slide_layouts[1]
        )

        self.add_header(slide, prs)

        slide.shapes.title.text = (
            "Key Metrics"
        )

        metric_text = ""

        for metric, values in analysis_result["kpis"].items():

            metric_text += (
                f"{metric}\n"
                f"Average: {values['mean']}\n"
                f"Maximum: {values['max']}\n"
                f"Minimum: {values['min']}\n\n"
            )

        slide.placeholders[1].text = metric_text

        # =========================
        # KEY INSIGHTS
        # =========================

        slide = prs.slides.add_slide(
            prs.slide_layouts[1]
        )

        self.add_header(slide, prs)

        slide.shapes.title.text = (
            "Key Insights"
        )

        clean_lines = self.clean_insights(
            insights
        )

        insight_text = ""

        for line in clean_lines:

            insight_text += (
                f"• {line}\n\n"
            )

        slide.placeholders[1].text = (
            insight_text
        )

        # =========================
        # CHART SLIDES
        # =========================

        chart_titles = [
            "Category Performance",
            "Distribution Analysis",
            "Correlation Analysis",
            "Trend Analysis"
        ]

        for i, chart_path in enumerate(chart_paths):

            slide = prs.slides.add_slide(
                prs.slide_layouts[5]
            )

            self.add_header(slide, prs)

            title = (
                chart_titles[i]
                if i < len(chart_titles)
                else f"Visualization {i+1}"
            )

            title_box = slide.shapes.add_textbox(
                Inches(0.3),
                Inches(0.5),
                Inches(5),
                Inches(0.5)
            )

            title_box.text = title

            slide.shapes.add_picture(
                chart_path,
                Inches(0.5),
                Inches(1),
                width=Inches(8.5)
            )

        # =========================
        # RECOMMENDATIONS
        # =========================

        slide = prs.slides.add_slide(
            prs.slide_layouts[1]
        )

        self.add_header(slide, prs)

        slide.shapes.title.text = (
            "Business Recommendations"
        )

        recommendations = """
• Focus on high-performing categories.

• Monitor KPI trends regularly.

• Investigate outliers and anomalies.

• Improve visibility of top-performing entities.

• Continue leveraging data-driven decision making.
"""

        slide.placeholders[1].text = (
            recommendations
        )

        # =========================
        # THANK YOU
        # =========================

        slide = prs.slides.add_slide(
            prs.slide_layouts[0]
        )

        slide.shapes.title.text = (
            "Thank You"
        )

        slide.placeholders[1].text = (
            "Generated by Analytics AI"
        )

        os.makedirs(
            "reports",
            exist_ok=True
        )

        ppt_path = (
            "reports/Analytics_Report.pptx"
        )

        prs.save(ppt_path)

        return ppt_path